kadai_010/crud/models.py
from django.db import models
from django.urls import reverse
   
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
       
    def __str__(self):
        return self.name
    
     # 新規作成・編集完了時のリダイレクト先
    def get_absolute_url(self):
        return reverse('list')

kadai_010/crud/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Product
from django.urls import reverse_lazy

class TopView(TemplateView):
    template_name = "top.html"

class ProductListView(ListView):
    model = Product
    paginate_by = 3

class ProductCreateView(CreateView):
    model = Product
    fields = '__all__'

class ProductUpdateView(UpdateView):
    model = Product
    fields = '__all__'
    template_name_suffix = '_update_form'

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('list')

class ProductDetailView(DetailView):
    model = Product
    template_name = 'crud/product_detail.html'

kadai_010/crud/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
   <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

kadai_010/crud/templates/crud/product_detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>商品詳細</title>
</head>
<body>
    <h1>商品詳細</h1>
    <h2>{{ object.name }}</h2>
    
    <table>
        <tr>
            <th>商品名</th>
            <td>{{ object.pk }}</td>
        </tr>
        <tr>
            <th>価格</th>
            <td>{{ object.price }}円</td>
        </tr>
    </table>
    
    <a href="{% url 'crud:product_list' %}">一覧へ戻る</a>

</body>
</html>

kadai_010/crud/templates/crud/product_list.html
{% extends "base.html" %}

{% block title %}商品一覧{% endblock %}
{% block content %}
<h1>商品一覧</h1>
<a href="{% url 'new' %}">新規作成</a>
<table class="table table-striped table-hover table-bordered">
   <thead>
       <tr>
           <th>商品名</th>
           <th>価格</th>
           <th>アクション</th>
       </tr>
   </thead>
   {% for product in object_list %}
   <tr>
       <td>{{ product.name }}</td>
       <td>{{ product.price }} 円</td>
       <tb>
        <a href="{% url 'product_detail' pk=product.pk %}">詳細</a>
       </tb>
　　　　<td>
            <button class="btn btn-primary" onclick="location.href='{% url 'edit' pk=product.pk %}'">編集</button>
            <button class="btn btn-danger" onclick="location.href='{% url 'delete' pk=product.pk %}'">削除</button>
       </td>
   </tr>
   {% endfor %}
</table>

    {# ページの表示 #}
    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} ページ<br>

    {# 前へ #}
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 先頭</a>
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
    {% endif %}

    {# 次へ #}
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">最後 &raquo;</a>
    {% endif %}
    {% endblock %}